return {
    'halloween',
    'carnival',
    'ghosts',
    'trick or treat',
    'costume',
    'candy',
    'candycorn',
    'snickers',
    'reeses cups',
    'candied apples',
    'ghouls',
    'goblin',
    'frankenstein',
    'graveyard',
    'haunted house',
    'monster',
    'scary',
    'spooky',
    'dracula',
    'mummy',
    'vampire',
    'bat',
    'devils night',
    'bloodcurdling',
    'scream',
    'horror',
    'thankskilling',
    'jason',
    'freddy krueger',
    'saw',
    'creepy',
    -- 'headless horseman', -- Too long 
    'ichabod crane',
    'decapitated',
    'raven',
    'edgar allen poe',
    'werewolf',
    'werewolves',
    'fright',
    'fright night',
    'cemetery',
    'cobwebs',
    'spider',
    'tarantula',
    'casket',
    'cauldron',
    'witch',
    'broom',
    'witchs brew',
    'corpse',
    'eerie',
    'cackle',
    'bloody',
    'bones',
    'skeleton',
    'crypt',
    'cryptkeeper',
    'grim reaper',
    'pumpkin',
    'apple cider',
    'pumpkin spice',
    'pumpkin carving',
    'jack o lantern',
    'mausoleum',
    'mummy',
    'owl',
    'black lodge',
    'howling',
    'occult',
    'shadow',
    'spectre',
    'poltergeist',
    'warlock',
    'undead',
    'zombie',
    'wraith',
    'zombie',
    'casper',
    'great pumpkin',
    'hocus pocus',
    'nightmare',
    'scream',
    'michael myers',
    'jason voorhees',
    -- 'friday the thirteenth', -- Too long 
    'october',
    -- 'october thirty first', -- Too long
}
